replicaCount: 1
timezone: America/New_York

image:
  repository: skyffxi/topaz-connect
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  ports:
    data: 31230
    auth: 31231
    view: 31001
    message: 31003

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

config:
  serverName: SkyFFXI
  timestampFormat: "[%d/%b %H:%M]"
  consoleVerbosity: 0
  ports:
    data: 54230
    auth: 54231
    view: 54001
    message: 54003
  database:
    host: localhost
    port: 3306
    username: root
    password: root
    name: skyffxi
  search:
    port: 54002
  message:
    host: "127.0.0.1"
    port: 54003
  logUserIP: false
  enableAccountCreation: true
  maintenanceMode: 0
  expectedClientVersion: "30201006_1"
