apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topazConnect.labels" . | nindent 4 }}
data:
  login.conf: |
    #Topaz login server conf

    #--------------------------------
    #login server parametres
    #--------------------------------

    #Time-stamp format which will be printed before all messages.
    #Can at most be 20 characters long.
    #Common formats:
    # %I:%M:%S %p (hour:minute:second 12 hour, AM/PM format)
    # %H:%M:%S (hour:minute:second, 24 hour format)
    # %d/%b/%Y (day/Month/year)
    #For full format information, consult the strftime() manual.
    timestamp_format: {{ .Values.config.timestampFormat }}

    #If redirected output contains escape sequences (color codes)
    stdout_with_ansisequence: no

    #Makes server output more silent by omitting certain types of messages:
    #Standard     = 1
    #Status       = 2
    #Info         = 4
    #Notice       = 8
    #Warn         = 16
    #Debug        = 32
    #Error        = 64
    #Fatal Error  = 128
    #SQL          = 256
    #Lua          = 512
    #Navmesh      = 1024
    #Action       = 2048
    #Exploit      = 4096
    #Example: "console_silent: 7" Hides standard, status and information messages (1+2+4)
    console_silent: {{ .Values.config.consoleVerbosity }}

    #--------------------------------
    #TCP/IP parameters
    #--------------------------------

    login_data_ip: 0.0.0.0
    login_data_port: {{ .Values.config.ports.data }}
    login_view_ip: 0.0.0.0
    login_view_port: {{ .Values.config.ports.view }}
    login_auth_ip: 0.0.0.0
    login_auth_port: {{ .Values.config.ports.auth }}

    #--------------------------------
    #SQL parameters
    #--------------------------------

    mysql_host:      {{ .Values.config.database.host }}
    mysql_port:      {{ .Values.config.database.port }}
    mysql_login:     {{ .Values.config.database.username }}
    mysql_password:  {{ .Values.config.database.password }}
    mysql_database:  {{ .Values.config.database.name }}

    #Search Server Port
    search_server_port: {{ .Values.config.search.port }}

    #Server name (not longer than 15 characters)
    servername: {{ .Values.config.serverName }}

    #Central message server settings (ensure these are the same on both all map servers and the central (lobby) server
    msg_server_port: {{ .Values.config.message.port }}
    msg_server_ip: {{ .Values.config.message.host }}

    #Logging of user IP address to database (true/false)
    log_user_ip: {{ .Values.config.logUserIP }}

    #Allow account creation via the loader (true/false)
    account_creation: {{ .Values.config.enableAccountCreation }}

  maint.conf: |
    #0 - disabled (normal operation)
    #1 - enabled (only GM characters allowed online, no new character creation)
    MAINT_MODE: {{ .Values.config.maintenanceMode }}

  version.conf: |
    #Topaz Version Info

    #Expected Client version (wrong version cannot log in)
    CLIENT_VER: {{ .Values.config.expectedClientVersion }}

    #WE STRONGLY ADVISE AGAINST LOCKING THE SERVER TO OLDER VERSIONS. IT IS A UNIVERSALLY BAD IDEA.

    #0 - disabled (every version allowed)
    #1 - enabled - strict (only exact CLIENT_VER allowed, default)
    #2 - enabled - greater than or equal  (matching or greater than CLIENT_VER allowed)
    VER_LOCK: 2

    #Current Server Version.
    #TOPAZ_VER: R202008-01

  packet_tcp.conf: |
    // Topaz tcp sockets Configuration file

    // Display debug reports (When something goes wrong during the report, the report is saved.)
    debug: {{ .Values.config.packets.debugTCP }}

    // How long can a socket stall before closing the connection (in seconds)
    stall_time: {{ .Values.config.packets.stallTime }}

    //----- IP Rules Settings -----

    // If IP's are checked when connecting.
    // This also enables DDoS protection.
    enable_ip_rules: {{ .Values.config.packets.enableIPRules }}

    // Order of the checks
    //   deny,allow     : Checks deny rules, then allow rules. Allows if no rules match.
    //   allow,deny     : Checks allow rules, then deny rules. Allows if no rules match.
    //   mutual-failure : Allows only if an allow rule matches and no deny rules match.
    // (default is deny,allow)

    order: {{ .Values.config.packets.checkOrder }}
    // order: allow,deny
    // order: mutual-failture

    // IP rules
    //   allow : Accepts connections from the ip range (even if flagged as DDoS)
    //   deny  : Rejects connections from the ip range
    // The rules are processed in order, the first matching rule of each list (allow and deny) is used

    // allow: 127.0.0.1
    // allow: 192.168.0.0/16
    // allow: 10.0.0.0/255.0.0.0
    // allow: all

    // deny: 127.0.0.1


    //---- DDoS Protection Settings ----
    // If ddos_count connection request are made within ddos_interval msec, it assumes it's a DDoS attack

    // Consecutive attempts interval (msec)
    // (default is 3000 msecs, 3 seconds)
    ddos_interval: {{ .Values.config.packets.ddos.interval }}

    // Consecutive attempts trigger
    // (default is 5 attemps)
    ddos_count: {{ .Values.config.packets.ddos.count }}

    // The time interval after which the threat of DDoS is assumed to be gone. (msec)
    // After this amount of time, the DDoS restrictions are lifted.
    // (default is 600000 msecs, 10 minutes)
    ddos_autoreset: {{ .Values.config.packets.ddos.autoReset }}


    //import: conf/import/packet_conf.txt
