apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topazConnect.labels" . | nindent 4 }}
data:
  login.conf: | {{ .Values.configs.login | nindent 4 }}
  maint.conf: | {{ .Values.configs.maint | nindent 4 }}
  version.conf: | {{ .Values.configs.version | nindent 4 }}
