apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topazConnect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: data
    port: {{ .Values.service.ports.data }}
    targetPort: data
  - name: auth
    port: {{ .Values.service.ports.auth }}
    targetPort: auth
  - name: view
    port: {{ .Values.service.ports.view }}
    targetPort: view
  selector:
    {{- include "topazConnect.selectorLabels" . | nindent 4 }}
