replicaCount: 1
timezone: America/New_York

image:
  repository: skyffxi/topaz-search
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  ports:
    search: 31002

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

config:
  packets:
    debugTCP: no
    stallTime: 60
    enableIPRules: yes
    checkOrder: deny,allow
    ddos:
      interval: 3000
      count: 5
      autoReset: 600000
  ports:
    search: 54002
  database:
    host: localhost
    port: 3306
    username: root
    password: root
    name: skyffxi
  expireAuctions: 1
  expireDays: 3
  expireInterval: 3600
